import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";

const noticePath = new URL("../../NOTICE.md", import.meta.url);
const knownLicenseLabels = new Set([
  "0BSD",
  "Apache-2.0",
  "BSD-3-Clause",
  "CC-BY-4.0",
  "ISC",
  "LGPL-3.0-or-later",
  "MIT",
  "MIT-0",
  "MPL-2.0",
  "Unlicense",
]);

function fail(message) {
  console.error(`[license-notice] ${message}`);
  process.exitCode = 1;
}

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function collectInventory(report) {
  if (!isRecord(report)) {
    throw new Error("pnpm licenses output was not an object");
  }

  const inventory = new Map();
  for (const [licenseLabel, packages] of Object.entries(report)) {
    if (!knownLicenseLabels.has(licenseLabel)) {
      throw new Error(
        `unreviewed licence label ${JSON.stringify(licenseLabel)}; review the exact package and update the governance baseline`,
      );
    }
    if (!Array.isArray(packages)) {
      throw new Error(`licence group ${licenseLabel} was not an array`);
    }

    const packageVersions = new Map();
    for (const packageEntry of packages) {
      if (
        !isRecord(packageEntry) ||
        typeof packageEntry.name !== "string" ||
        !Array.isArray(packageEntry.versions) ||
        packageEntry.versions.some((version) => typeof version !== "string") ||
        packageEntry.license !== licenseLabel
      ) {
        throw new Error(`licence group ${licenseLabel} contained malformed metadata`);
      }

      const versions = packageVersions.get(packageEntry.name) ?? new Set();
      for (const version of packageEntry.versions) {
        versions.add(version);
      }
      packageVersions.set(packageEntry.name, versions);
    }
    inventory.set(licenseLabel, packageVersions);
  }

  return inventory;
}

function renderNotice(inventory) {
  const lines = [
    "# Third-party dependency notice inventory",
    "",
    "This repository is private and first-party code remains subject to `LICENSE.md`.",
    "Third-party packages retain their own rights and obligations. This generated",
    "inventory records package-declared SPDX labels; it is not a legal compatibility",
    "decision and does not replace the exact licence text, copyright notice, NOTICE",
    "file, source offer, attribution, or modification record required by a delivered",
    "artifact.",
    "",
    "Generated by `pnpm governance:notices` from the installed pnpm workspace graph.",
    "`pnpm governance:licenses` fails when this inventory drifts or a new licence label",
    "appears without review.",
    "",
    "## Declared licence inventory",
    "",
  ];

  for (const licenseLabel of [...inventory.keys()].sort()) {
    lines.push(`### ${licenseLabel}`, "");
    const packages = inventory.get(licenseLabel);
    for (const packageName of [...packages.keys()].sort()) {
      const versions = [...packages.get(packageName)].sort();
      lines.push(`- ${packageName}@${versions.join(", ")}`);
    }
    lines.push("");
  }

  lines.push(
    "## Release and handoff boundary",
    "",
    "Before packaging, deploying, publishing, or handing off an artifact, follow",
    "`docs/governance/dependency-license-and-notice-process.md`. Re-run the inventory",
    "for the target platform and production dependency set, inspect the exact package",
    "contents, and bundle every required third-party licence and notice. Platform-",
    "specific optional packages and generated client artifacts can differ from this",
    "Linux CI inventory.",
    "",
  );

  return `${lines.join("\n")}\n`;
}

const pnpmExecutable = process.platform === "win32" ? "pnpm.cmd" : "pnpm";
const result = spawnSync(pnpmExecutable, ["licenses", "list", "--json"], {
  encoding: "utf8",
  stdio: ["ignore", "pipe", "pipe"],
});

if (result.error || result.status !== 0) {
  fail(
    result.error?.message ?? result.stderr.trim() ?? "pnpm licenses list failed",
  );
} else {
  try {
    const notice = renderNotice(collectInventory(JSON.parse(result.stdout)));
    if (process.argv.includes("--write")) {
      await writeFile(noticePath, notice, "utf8");
      console.log("[license-notice] WROTE NOTICE.md");
    } else if (process.argv.includes("--check")) {
      const currentNotice = await readFile(noticePath, "utf8");
      if (currentNotice !== notice) {
        throw new Error(
          "NOTICE.md is stale; run pnpm governance:notices and review the dependency/licence change",
        );
      }
      console.log("[license-notice] PASS NOTICE.md matches the installed dependency graph");
    } else {
      process.stdout.write(notice);
    }
  } catch (error) {
    fail(error instanceof Error ? error.message : String(error));
  }
}
