import type { ResolvedDesign } from "../decisions.js";
import type { InteractionPlan } from "../interaction-decisions.js";
import { titleCase } from "./content.js";

/** The route IDs this starter knows how to compose, and where each lives. */
export const KNOWN_ROUTES: Readonly<
  Record<string, { readonly component: string; readonly module: string }>
> = {
  home: { component: "HomeRoute", module: "./routes/HomeRoute" },
  "services-index": {
    component: "ServicesIndexRoute",
    module: "./routes/ServicesRoutes",
  },
  "service-detail": {
    component: "ServiceDetailRoute",
    module: "./routes/ServicesRoutes",
  },
  "projects-index": {
    component: "ProjectsIndexRoute",
    module: "./routes/ProjectsRoutes",
  },
  "project-detail": {
    component: "ProjectDetailRoute",
    module: "./routes/ProjectsRoutes",
  },
  about: { component: "AboutRoute", module: "./routes/AboutContactRoutes" },
  contact: { component: "ContactRoute", module: "./routes/AboutContactRoutes" },
};

/**
 * Emits the experience entrypoint — the one module the Platform loads.
 *
 * Only the routes this client's page graph actually references are imported and
 * registered, so a client with no projects ships no project route source at all.
 */
export function emitEntrypoint(
  design: ResolvedDesign,
  routeIds: readonly string[],
): string {
  const { brief } = design;
  const byModule = new Map<string, string[]>();
  for (const routeId of routeIds) {
    const entry = KNOWN_ROUTES[routeId];
    if (entry === undefined) continue;
    byModule.set(entry.module, [
      ...(byModule.get(entry.module) ?? []),
      entry.component,
    ]);
  }
  byModule.set("./routes/AboutContactRoutes", [
    ...new Set([
      ...(byModule.get("./routes/AboutContactRoutes") ?? []),
      "NotFoundRoute",
    ]),
  ]);

  const imports = [...byModule.entries()]
    .sort(([left], [right]) => (left < right ? -1 : 1))
    .map(([module, components]) => {
      const named = [...new Set(components)].sort();
      return named.length === 1
        ? `import { ${named[0]} } from "${module}";`
        : `import {\n${named.map((name) => `  ${name},`).join("\n")}\n} from "${module}";`;
    })
    .join("\n");

  const routes = routeIds
    .filter((routeId) => KNOWN_ROUTES[routeId] !== undefined)
    .map((routeId) => {
      const component = KNOWN_ROUTES[routeId]?.component ?? "";
      return /^[a-z][a-zA-Z0-9]*$/.test(routeId)
        ? `    ${routeId}: ${component},`
        : `    "${routeId}": ${component},`;
    })
    .join("\n");

  return `import { defineClientExperience } from "@proportion/client-experience";

${imports}

/**
 * ${titleCase(brief.experienceId)} — Client Experience.
 *
 * Generated by the Proportion P1 Experience Starter from this client's build
 * package, then owned outright by this client. The generator is a source
 * accelerator: nothing below imports it, and this site builds, installs and
 * deploys with no knowledge that it ever existed.
 *
 * ${brief.creative.thesis}
 */
export const authoredClientExperience = defineClientExperience({
  schemaVersion: 1,
  experienceId: "${brief.experienceId}",
  experienceVersion: "${brief.experienceVersion}",
  routes: {
${routes}
  },
  notFound: NotFoundRoute,
});

export default authoredClientExperience;
`;
}

/** Emits the manifest the Platform validates the experience against. */
export function emitManifest(
  design: ResolvedDesign,
  routeIds: readonly string[],
  plan: InteractionPlan,
): string {
  const { brief } = design;
  return `${JSON.stringify(
    {
      schemaVersion: 1,
      kind: "AUTHORED_CLIENT_EXPERIENCE",
      experienceId: brief.experienceId,
      experienceVersion: brief.experienceVersion,
      entrypoint: "index.tsx",
      designDnaPath: "design-dna.json",
      routeIds: [...routeIds],
      signatureIds: [],
      // A generated P1 experience declares no dependency. Baseline motion, when
      // present, is one client-local component over native browser APIs.
      publicDependencies: [],
      runtime: {
        clientJavaScript:
          plan.usesReveal || plan.usesDisclosure || plan.usesMediaExplorer
            ? "COMPONENT_SCOPED"
            : "NONE",
        /*
         * What this artifact actually does, not what one subset of its design
         * inputs asked for. A client can select no entrance and no pointer
         * feedback and still receive a folding question run or a media overlay,
         * both of which animate; reading `interaction.enabled` here would have
         * declared that site still.
         */
        motion: plan.animates ? "NATIVE" : "NONE",
        reducedMotion: "REQUIRED",
      },
    },
    null,
    2,
  )}\n`;
}
